kind: ConfigMap
apiVersion: v1
metadata:
  name: mysql-config
  namespace: app
  labels:
    app: mysql
    version: v8.0.28
data:
  my.cnf: |-
    [mysql]
    default-character-set=utf8mb4
    [client]
    default-character-set=utf8mb4
    [mysqld]
    max_connections = 2000
    secure_file_priv=/var/lib/mysql
    sql_mode=STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION
