kind: Service
apiVersion: v1
metadata:
  name: mysql
  namespace: app
  labels:
    app: mysql
    version: v8.0.28
spec:
  type: NodePort
  selector:
    app: mysql
    version: v8.0.28
  ports:
    - name: mysql
      port: 3306
      targetPort: 3306
