kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: mysql
  namespace: app
  labels:
    app: mysql
    version: v8.0.28
spec:
  replicas: 1
  serviceName: mysql
  selector:
    matchLabels:
      app: mysql
      version: v8.0.28
  template:
    metadata:
      labels:
        app: mysql
        version: v8.0.28
    spec:
      nodeSelector:
        app: "true"
      containers:
        - name: mysql
          image: mysql:8.0.28
          imagePullPolicy: IfNotPresent
          securityContext:
            capabilities:
              add: ["SYS_PTRACE"]
          ports:
            - name: default
              containerPort: 3306
          args:
            - --character-set-server=utf8mb4
            - --collation-server=utf8mb4_general_ci
            - --default-authentication-plugin=mysql_native_password
          env:
            - name: TZ
              value: "Asia/Shanghai"
            - name: MYSQL_ROOT_PASSWORD
              value: "123456"
          volumeMounts:
            - name: localtime
              mountPath: /etc/localtime
            - name: data
              mountPath: /var/lib/mysql
            - name: config
              mountPath: /etc/mysql/my.cnf
              subPath: my.cnf
          resources:
            limits:
              cpu: 1000m
              memory: 1024Gi
            requests:
              cpu: 100m
              memory: 128Mi
      volumes:
        - name: localtime
          hostPath:
            path: /etc/localtime
        - name: config
          configMap:
            name: mysql-config
            items:
              - key: my.cnf
                path: my.cnf
        - name: data
          hostPath:
            type: ""
            path: /data/nfs/mysql/