apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka
  namespace: map
  labels:
    app: kafka
spec:
  replicas: 1
  serviceName: kafka
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      nodeSelector:
        map: "true"
      containers:
        - name: kafka
          image: bitnami/kafka:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9092
          env:
            - name: TZ
              value: "Asia/Shanghai"
            - name: KAFKA_BROKER_ID
              value: 1
            - name: KAFKA_CFG_LISTENERS
              value: "PLAINTEXT://:9092"
            - name: KAFKA_CFG_ADVERTISED_LISTENERS
              value: "PLAINTEXT://127.0.0.1:9092"
            - name: ALLOW_PLAINTEXT_LISTENER
              value: "yes"
            - name: KAFKA_CFG_ZOOKEEPER_CONNECT
              value: "zookeeper:2181"

---
apiVersion: v1
kind: Service
metadata:
  name: kafka
  namespace: map
  labels:
    app: kafka
spec:
  type: NodePort
  selector:
    app: kafka
  ports:
    - name: kafka-port
      port: 9092
      targetPort: 9092
      nodePort: 30092
      protocol: TCP
