apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: zookeeper
  namespace: default
  labels:
    app: zookeeper
spec:
  replicas: 1
  serviceName: zookeeper
  selector:
    matchLabels:
      app: zookeeper
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      containers:
        - name: zookeeper
          image: bitnami/zookeeper:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 2181
          env:
            - name: TZ
              value: "Asia/Shanghai"
            - name: ALLOW_ANONYMOUS_LOGIN
              value: "yes"

---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper
  namespace: default
  labels:
    app: zookeeper
spec:
  type: NodePort
  selector:
    app: zookeeper
  ports:
    - name: zookeeper
      port: 2181
      targetPort: 2181
